// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Utbildningsföretag.infrastructure.Persistance;

#nullable disable

namespace Utbildningsföretag.infrastructure.Migrations
{
    [DbContext(typeof(Utbildningdbcontext))]
    [Migration("20260215132847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Deltagare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.KursSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("KursId")
                        .HasColumnType("uuid")
                        .HasColumnName("kurs_id");

                    b.Property<Guid>("LärareId")
                        .HasColumnType("uuid")
                        .HasColumnName("lärare_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_course_sessions");

                    b.HasIndex("KursId")
                        .HasDatabaseName("ix_course_sessions_kurs_id");

                    b.HasIndex("LärareId")
                        .HasDatabaseName("ix_course_sessions_lärare_id");

                    b.ToTable("course_sessions", (string)null);
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Kurser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Lärare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Registrera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_session_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.HasKey("Id")
                        .HasName("pk_registrations");

                    b.HasIndex("CourseSessionId")
                        .HasDatabaseName("ix_registrations_course_session_id");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_registrations_participant_id");

                    b.ToTable("registrations", (string)null);
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.KursSession", b =>
                {
                    b.HasOne("Utbildningföretag.Domain.Entities.Kurser", "Kurs")
                        .WithMany("Sessions")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_sessions_courses_kurs_id");

                    b.HasOne("Utbildningföretag.Domain.Entities.Lärare", "Lärare")
                        .WithMany("Sessions")
                        .HasForeignKey("LärareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_sessions_teachers_lärare_id");

                    b.Navigation("Kurs");

                    b.Navigation("Lärare");
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Registrera", b =>
                {
                    b.HasOne("Utbildningföretag.Domain.Entities.KursSession", "CourseSession")
                        .WithMany("Registrations")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registrations_course_sessions_course_session_id");

                    b.HasOne("Utbildningföretag.Domain.Entities.Deltagare", "Participant")
                        .WithMany("Registrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registrations_participants_participant_id");

                    b.Navigation("CourseSession");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Deltagare", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.KursSession", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Kurser", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Utbildningföretag.Domain.Entities.Lärare", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
